Fix coveralls reporting
Summary:
😅 oops. sorry. 😄

Recent changes broke this.

Error: `/Users/travis/build.sh: line 57: slather: command not found`

https://travis-ci.org/Instagram/IGListKit/jobs/177084719#L697
Closes https://github.com/Instagram/IGListKit/pull/223

Differential Revision: D4206344

Pulled By: rnystrom

fbshipit-source-id: b20ae4c637eef3744306771fc65acae9ec76bdbc