Fixing Build Issues when Running IGListKit-tvOSTests
Summary:
tvOS Tests were failing because `IGListAdapterUpdateTester` was being used by `IGListAdapterE2ETests` but `IGListAdapterUpdateTester` was not included in the tvOS Target.

Error Msg:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IGListAdapterUpdateTester", referenced from:
      objc-class-ref in IGListAdapterE2ETests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Reviewed By: rnystrom

Differential Revision: D6251880

fbshipit-source-id: 463452c2206bac79e9c5738306b61c693ea580ca